import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import { useEffect, useState } from 'react'
const Manual: NextPage = () => {

  const [num, setNum] = useState(0)

  const addNum = () => {
    setNum(num + 1)
  }
  const subNum = () => {
    setNum(num - 1)
  }


    return (
      <div className='app'>
        <Head>
          <title>Manual</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="https://i.kym-cdn.com/entries/icons/original/000/027/486/Screen_Shot_2018-10-26_at_11.49.18_AM.jpg" />
        </Head>
  
        <main className='idk'>
          <h2>Manual Page</h2>

          <button onClick={addNum}>+</button>
          <h1>{num}</h1>
          <button onClick={subNum}>-</button>
        </main>
  
        
      </div>
      
    )
  }

  export default Manual
