import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import { useEffect, useState } from 'react'
const Auto: NextPage = () => {
  const [num, setNum] = useState(0)
  useEffect(() => {
      const interval = setInterval(() => {
      setNum(num + 1);
      return () => clearInterval(interval);
    }, 3000);
    
  }, [num]);

    return (
      <div className='app'>
        <Head>
          <title>Auto</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="https://i.kym-cdn.com/entries/icons/original/000/027/486/Screen_Shot_2018-10-26_at_11.49.18_AM.jpg" />
        </Head>
  
        <main className='idk'>
          <h2>Auto Page</h2>
          <h1>{num}</h1>
        </main>
  
        
      </div>
      
    )
  }

  export default Auto
